services:
  db:
    image: postgres:15
    restart: always
    container_name: payments_db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rabbitmq-network

  server:
    build:
      context: .
    container_name: payments_service
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/payments_db
    ports:
      - 6001:6001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks: 
      - rabbitmq-network
  
  
networks: 
  rabbitmq-network: 
    external: true

volumes:
  db_data:
