services:
  db:
    image: postgres:15
    restart: always
    container_name: billing_db
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rabbitmq-network

  server:
    build:
      context: .
    container_name: billing_service
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/billing_db
      PORT: 6002
      RABBITMQ_URL: "amqp://rabbitmq:5672"
    ports:
      - "6002:6002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    external: true

volumes:
  db_data:
